{% set version = "0.14.0" %}

package:
    name: biggus
    version: {{ version }}

source:
    fn: v{{ version }}.tar.gz
    url: https://github.com/SciTools/biggus/archive/v{{ version }}.tar.gz
    sha256: 16188881998253d124ce8aa924b35f3f466aff06b975c818b56a0663732ba314

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy

test:
    imports:
        - biggus

about:
    home: https://pypi.python.org/pypi/Biggus
    license: LGPLv3
    summary: Virtual large arrays and lazy evaluation.

extra:
    recipe-maintainers:
        - pelson
        - rhattersley
        - ocefpaf
